### ISSUE TITLE
Fullstack-project review

### ISSUE THREAD

**Issue by ShootingStar91** [sonicsasha/eLection#11]
# Fullstack-project review 

This is a review of your Fullstack practice project. You may apply the suggestions presented here if you so wish, but you do not have to implement any further changes to receive the credits for your project.

### Feedback on the user experience

+ Nice, unique style
+ Easy and simple to start an election.
+ Actions impact other clients immediately. Smooth experience!
+ I was confused after the election ended and the client-app said "Look at the results screen" - the host did not have "Show results" button but instead the results were found from "Open the viewer window", perhaps that should be named differently?
+ There are also nice transition animations!
+ Mainly, everything seems quite simple and robust. Here are just minor improvements that come to mind:
  + For the style, I would hide the scrollbar unless it is necessary (`overflow: auto`), or try to order the things on screen so that the scroll bar is not necessary in most cases.
  + The bright red and green don't really fit the strong purple theme (though now I read the theme is meant to be customizable, so I guess this is less of an issue.)

### Feedback on the code

Backend

+ The code is good TypeScript. Very readable and well-organized - though perhaps lobbyservice.ts is a bit too long at over 400 lines.
+ Middlewares used well
+ Websockets used nicely to push changes immediately to clients and host, with no need for polling requests.

Frontend

+ I strongly recommend a linter and using much smaller indentation. It is quite difficult to read the code. Some files seem to have 8 indentation while others only 4.
+ Making requests is much easier with some external library such as React Query. They bring a little bit of boilerplate code, but then you do not have to handle things like loading state, caching, authorization, error handling etc. for every query separately (What is happening [here](https://github.com/sonicsasha/eLection/blob/b1e253f189694eba281738c0ae4209b98257c551/frontend/src/routes/Participant.tsx#L26))?
+ Otherwise, the code is well organized and readable (apart from the indentation issue).
+ Context API is used well
+ Nice job for making the app internationalized and styles customizable! Something I seldom see in the practice projects, but is a great idea and especially 118n is often necessary in real-world apps.

### Summary

The idea for the project is great, I think this is a real need for many situations. It works and is easy to use, and has a customizable layout. Websockets are well-utilized and necessary for this kind of application. Great work all around! :tada:

**Comment by sonicsasha** [comment]
Thank you for the kind feedback! :) Most of the issues should now hopefully be fixed in [version 1.1.3](https://github.com/sonicsasha/eLection/releases/tag/v1.1.3).

The issue with the scrollbar was a surprise, as it was not an issue on my system. It looks like Windows 11 automatically hides the scrollbar if necessary, but some other systems (such as Windows 10) do not do this. This should now be fixed. Thank you for bringing this up!

As for React Query, I did consider using it at the start of the project, but I believed that it would not really suit this kind of real-time web app. Most of the information is transferred through websockets and there wasn't a need for caching (besides storing information about lobbies). React Query could probably make the code a bit cleaner, but implementing it now would require a lot of refactoring, so for now I'll shelve it for the future.
